export { seoConfig } from './seo.config'
export { organizationSchema } from './schemas/organization'
export { localBusinessSchema } from './schemas/localBusiness'
export { websiteSchema } from './schemas/website'
export { breadcrumbSchema } from './schemas/breadcrumb'
export { serviceSchema, allServicesSchema } from './schemas/service'
export { faqSchema } from './schemas/faq'
export { blogPostingSchema } from './schemas/blogPosting'
export { articleSchema } from './schemas/article'

export type { BreadcrumbItem } from './schemas/breadcrumb'
export type { ServiceInput } from './schemas/service'
export type { FaqItem } from './schemas/faq'
export type { BlogPostingInput } from './schemas/blogPosting'
export type { ArticleInput } from './schemas/article'
